###

POST https://afqs3iwavc.execute-api.eu-west-1.amazonaws.com/Prod/readdb HTTP/1.1
content-type: application/json

{
  "id": "4"
}


###

POST https://afqs3iwavc.execute-api.eu-west-1.amazonaws.com/Prod/writedb HTTP/1.1
content-type: application/json

{
  "id": "4",
  "labels": {
    "congrats": "Grazie,",
    "subscriptionIsActive": "il tuo abbonamento è ora attivo!",
    "yourChoice": "La tua scelta",
    "contentAvailability": "Contenuti sempre disponibili su PC, tablet e smartphone",
    "subscriptionType": "Tipologia abbonamento",
    "automaticRenew": "Offerta a rinnovo automatico disattivabile in ogni momento",
    "allOffers": "Vedi tutte le offerte",
    "clickHere": "Continua a leggere",
    "backToArticle": "per tornare all\"articolo"
  }
}

###

POST https://afqs3iwavc.execute-api.eu-west-1.amazonaws.com/Prod/writedb HTTP/1.1
content-type: application/json

{
  "id": "5",
  "name": "mock4",
  "labels": {
    "first_name": "Car",
    "last_name": "Rands",
    "email": "crands2@vimeo.com",
    "gender": "Non-binary",
    "ip_address": "66.85.242.75"
  }
}
