AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  labelsDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: italian
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LambdaWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionWrite/
      Handler: write.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /label
            Method: post
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref labelsDB

  LambdaRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionRead/
      Handler: read.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /label
            Method: get
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref labelsDB
