AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  labelsDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Labels
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LabelsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true

  LambdaWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionWrite/
      Handler: write.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            RestApiId: !Ref LabelsApi
            Path: /label
            Method: post
            Auth:
              ApiKeyRequired: true
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref labelsDB

  LambdaRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionRead/
      Handler: read.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            RestApiId: !Ref LabelsApi
            Path: /label
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref labelsDB

  LambdaDelete:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functionDelete/
      Handler: delete.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            RestApiId: !Ref LabelsApi
            Path: /label
            Method: delete
            Auth:
              ApiKeyRequired: true
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref labelsDB
